### ISSUE TITLE
ESP8266/RobotDyn

### ISSUE THREAD

**Issue by NicBout** [fabianoriccardi/dimmable-light#19]
Thanks for this nice library. 
Unfortunately, I doesn't seem to work for me. Everything compiles and flashes fine in the Arduino IDE. I don't seem to be getting my circuit to work. I use the ubiquitous RobotDyn 1 channel dimmer and an ESP8266 12F NodeMCU.
No light, whatever the sketch...
- I have checked the board and the thyristor pin is operational, so is the zero cross pin (I can read values coming in using serial.read() so I assume this side is fine as well).
- I have tried different Nodemcu boards of the same type, with the same result.
- I have tried changing a few parameters in the thyristor.cpp file but this didn't change anything.
- I have also tried to downgrade my Esp8266 framework version to older versions with no effect.
- I have completely removed the Arduino IDE and downloaded the libraries again in case something was cached somewhere that would cause the issue with no success either.
I think the timing doesn't get recognised for some reason, the cause of which I am at a loss to find.

I am using a Mac, latest OS version, the latest version of the Arduino IDE, ESP8266 Framework 2.7.4, and the current Dimmable lights code from GitHub.
Would anyone have any idea?
Many thanks

**Comment by fabianoriccardi** [comment]
Sorry for the very late reply... I'm closing this issue since very long time has passed, frameworks and this library were updated in the meantime and, currently, I don't see any issue on ESP8266. 

However, if this issue is still relevant to you, please tell me and I will investigate it.
