### ISSUE TITLE
Phase Control

### ISSUE THREAD

**Issue by ddesign** [fabianoriccardi/dimmable-light#20]
Hi,

First, thanks for a great library. I have been working with an ESP32, previously Arduino, and having mixed results achieving my aims. We've actually gone down the route of moving all of the interrupt / timings to electronics via a 555 timer, transistor, moc3011 and triac (BTA16), fed from the zero cross n4525/35.  The main reason, due to the limitations of arduino / interrupts hogging all the resources.

All we need to provide now is which side of the sine wave we want (a digital HIGH or LOW) and how much power (PWM). However, I really would like to get this working, considering the time I have already put into it :)

I have a niche case where I need to phase control a 20v A/C supply to provide power to a DC motor that needs to run either way depending on which half of the sine wave is chopped. I can't change the the components as I am modding an already existing setup.

I have been testing with the first example 1_dimmable_light, and have got reasonable results by flipping a flag and dropping out of zero_cross_int() on every other interrupt, here: https://github.com/fabiuz7/Dimmable-Light-Arduino/blob/90b0ce35b698eb19beb955a3353c3bf091899e0c/src/thyristor.cpp#L288 I assumed this was a good place, guessing that was the job of the definition above (#ifdef FILTER_INT_PERIOD):

![image](https://user-images.githubusercontent.com/746392/102112937-575d0b80-3e30-11eb-8106-5cc375d92dcb.png)

As you can see, I am getting random out of phase triggers, and the longer the brightening goes on the more out of phase pulses I get. Yellow is the interrupt and green is the anode on the MOC.

So, I moved on to the array / timer (Thyristor::setDelay). I attempted to skip entries there, which didn't work at all.

I feel like I am nearly there but would be very grateful for any insight, I am a seasoned programmer, but with easier languages. C is really forcing me to learn properly :) I do also want to be able to choose which half of the sine wave so I can get positive or negative to the DC motor.

Thanks for your time,

Andrew.

**Comment by fabianoriccardi** [comment]
Hi, sorry for long delay, probably this is issue doesn't matter to you anymore ... I might have been a bug, hopefully solved in the new versions. I'm closing this issue, but if you still need help, please tell me.
