### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by nsummy** [fabianoriccardi/dimmable-light#31]
Looking through the commits there have been many fixes, impovements, and modifications over the past few years.  Unfortunately  the last build was in 2019.  Anyone installing this from the Arduino IDE won't get the benefits of this hard work. Thanks :)

**Comment by fabianoriccardi** [comment]
I know, I'm revisiting the "latest" changes I have commited since the latest version, I'm going to release as soon as possible.

**Comment by nsummy** [comment]
Thank you, refreshing to see this is still under active development!

**Comment by fabianoriccardi** [comment]
The [new release ](https://github.com/fabianoriccardi/dimmable-light/commit/c7803314f92708f895227ede46426f68ac7863e4) is out! 🚀
