### ISSUE TITLE
Does not work with Wifi on ESP8266

### ISSUE THREAD

**Issue by heartwerker** [fabianoriccardi/dimmable-light#38]
Love this library a lot. now i meant to connect to wifi.

unfortunately when i am trying to combine it with the [tzapu/WiFiManager](https://github.com/tzapu/WiFiManager) library my (otherwise empty) project cant compile.

Using platformio, wemos d1 mini esp8266...

 _platformio.ini_:

```
[env:d1_mini]
platform = espressif8266@2.3.0
board = d1_mini
framework = arduino

lib_ldf_mode = deep+ # for wifimanager lib
lib_deps = 
    tzapu/WiFiManager@^0.16.0
	fabianoriccardi/Dimmable Light for Arduino@^1.5.0
```

_main.cpp_:

```
#include <Arduino.h>
void setup(){}
void loop(){}
```

_Error Output_:
```
Processing d1_mini (platform: espressif8266@2.3.0; board: d1_mini; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
Library Manager: Installing fabianoriccardi/Dimmable Light for Arduino @ ^1.5.0
Unpacking  [####################################]  100%
Library Manager: Dimmable Light for Arduino@1.5.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing ArduinoSTL
Unpacking  [####################################]  100%
Library Manager: ArduinoSTL@1.3.3 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (2.3.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 2.20601.191124 (2.6.1) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.20800.0 (2.8.0) 
 - toolchain-xtensa @ 2.40802.191122 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 44 compatible libraries
Scanning dependencies...
Dependency Graph
|-- WiFiManager @ 0.16.0
|-- Dimmable Light for Arduino @ 1.5.0
Building in release mode
Compiling .pio/build/d1_mini/src/main.cpp.o
Generating LD script .pio/build/d1_mini/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/ArduinoSTL.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/abi/abi.cpp.o
In file included from /Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:246:0,
                 from src/main.cpp:1:
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:53:13: error: 'function' in namespace 'std' does not name a type
     typedef std::function<void(size_t, size_t)> THandlerFunction_Progress;
             ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:19: error: expected ';' at end of member declaration
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                   ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:56: error: expected ')' before 'fn'
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                                                        ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:204:5: error: 'THandlerFunction_Progress' does not name a type
     THandlerFunction_Progress _progress_callback;
     ^
In file included from src/main.cpp:1:0:
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:251:12: error: 'std::isinf' has not been declared
 using std::isinf;
            ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:252:12: error: 'std::isnan' has not been declared
 using std::isnan;
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/algorithm.cpp.o
            ^
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/associative_base.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/bitset.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/char_traits.cpp.o
*** [.pio/build/d1_mini/src/main.cpp.o] Error 1
.pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:79:2: warning: #warning "printf() will not be functional on this platform." [-Wcpp]
 #warning "printf() will not be functional on this platform."
  ^
In file included from /Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:246:0,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.h:12,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:1:
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:53:13: error: 'function' in namespace 'std' does not name a type
     typedef std::function<void(size_t, size_t)> THandlerFunction_Progress;
             ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:19: error: expected ';' at end of member declaration
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                   ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:56: error: expected ')' before 'fn'
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                                                        ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:204:5: error: 'THandlerFunction_Progress' does not name a type
     THandlerFunction_Progress _progress_callback;
     ^
In file included from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.h:12:0,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:1:
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:251:12: error: 'std::isinf' has not been declared
 using std::isinf;
            ^
/Users/heartwerker/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:252:12: error: 'std::isnan' has not been declared
 using std::isnan;
            ^
*** [.pio/build/d1_mini/libacb/ArduinoSTL/ArduinoSTL.cpp.o] Error 1
======================================================================================================================= [FAILED] Took 3.02 seconds =======================================================================================================================

 *  The terminal process "platformio 'run', '--environment', 'd1_mini'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

 any ideas??????

**Comment by heartwerker** [comment]
There is also an Error when trying to use regular ESP8266 Wifi....

```
[env:d1_mini]
platform = espressif8266@2.3.0
board = d1_mini
framework = arduino

lib_deps = 
	fabianoriccardi/Dimmable Light for Arduino@^1.5.0

```

_main.cpp_:

```
#include <Arduino.h>
#include <ESP8266WiFi.h>
void setup(){}
void loop(){}
```


´´´
Processing d1_mini (platform: espressif8266@2.3.0; board: d1_mini; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Library Manager: Installing fabianoriccardi/Dimmable Light for Arduino @ ^1.5.0
Unpacking  [####################################]  100%
Library Manager: Dimmable Light for Arduino@1.5.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing ArduinoSTL
Unpacking  [####################################]  100%
Library Manager: ArduinoSTL@1.3.3 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (2.3.0) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 2.20601.191124 (2.6.1) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.20800.0 (2.8.0) 
 - toolchain-xtensa @ 2.40802.191122 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 43 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Dimmable Light for Arduino @ 1.5.0
|-- ESP8266WiFi @ 1.0
Building in release mode
Compiling .pio/build/d1_mini/src/main.cpp.o
Generating LD script .pio/build/d1_mini/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/ArduinoSTL.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/abi/abi.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/algorithm.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/associative_base.cpp.o
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/bitset.cpp.o
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:246:0,
                 from src/main.cpp:1:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:53:13: error: 'function' in namespace 'std' does not name a type
     typedef std::function<void(size_t, size_t)> THandlerFunction_Progress;
             ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:19: error: expected ';' at end of member declaration
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                   ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:56: error: expected ')' before 'fn'
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                                                        ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:204:5: error: 'THandlerFunction_Progress' does not name a type
     THandlerFunction_Progress _progress_callback;
     ^
In file included from src/main.cpp:1:0:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:251:12: error: 'std::isinf' has not been declared
 using std::isinf;
            ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:252:12: error: 'std::isnan' has not been declared
 using std::isnan;
            ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h:28:0,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:34,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:41:9: error: 'shared_ptr' in namespace 'std' does not name a type
 typedef std::shared_ptr<WiFiEventHandlerOpaque> WiFiEventHandler;
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:59:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onStationModeConnected(std::function<void(const WiFiEventStationModeConnected&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:60:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onStationModeDisconnected(std::function<void(const WiFiEventStationModeDisconnected&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:61:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onStationModeAuthModeChanged(std::function<void(const WiFiEventStationModeAuthModeChanged&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:62:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onStationModeGotIP(std::function<void(const WiFiEventStationModeGotIP&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:63:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onStationModeDHCPTimeout(std::function<void(void)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:64:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onSoftAPModeStationConnected(std::function<void(const WiFiEventSoftAPModeStationConnected&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:65:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onSoftAPModeStationDisconnected(std::function<void(const WiFiEventSoftAPModeStationDisconnected&)>);
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:66:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onSoftAPModeProbeRequestReceived(std::function<void(const WiFiEventSoftAPModeProbeRequestReceived&)>);
         ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h:28:0,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:34,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiGeneric.h:67:9: error: 'WiFiEventHandler' does not name a type
         WiFiEventHandler onWiFiModeChange(std::function<void(const WiFiEventModeChange&)>);
         ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:36:0,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiScan.h:38:37: error: 'std::function' has not been declared
         void scanNetworksAsync(std::function<void(int)> onComplete, bool show_Compiling .pio/build/d1_mini/libacb/ArduinoSTL/char_traits.cpp.o
hidden = false);
                                     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiScan.h:38:45: error: expected ',' or '...' before '<' token
         void scanNetworksAsync(std::function<void(int)> onComplete, bool show_hidden = false);
                                             ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:36:0,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFiScan.h:63:16: error: 'function' in namespace 'std' does not name a type
         static std::function<void(int)> _onComplete;
                ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/CertStoreBearSSL.h:26:0,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:30,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecure.h:41,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecure.h:20,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:41,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:37:9: error: 'shared_ptr' in namespace 'std' does not name a type
 typedef std::shared_ptr<FileImpl> FileImplPtr;
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:39:9: error: 'shared_ptr' in namespace 'std' does not name a type
 typedef std::shared_ptr<FSImpl> FSImplPtr;
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:41:9: error: 'shared_ptr' in namespace 'std' does not name a type
 typedef std::shared_ptr<DirImpl> DirImplPtr;
         ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:55:22: error: expected ')' before 'p'
     File(FileImplPtr p = FileImplPtr(), FS *baseFS = nullptr) : _p(p), _fakeDir(nullptr), _baseFS(baseFS) { }
                      ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:118:5: error: 'FileImplPtr' does not name a type
     FileImplPtr _p;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:121:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<Dir> _fakeDir;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:128:20: error: expected ')' before 'impl'
     Dir(DirImplPtr impl = DirImplPtr(), FS *baseFS = nullptr): _impl(impl), _baseFS(baseFS) { }
                    ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:145:5: error: 'DirImplPtr' does not name a type
     DirImplPtr _impl;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:201:18: error: expected ')' before 'impl'
     FS(FSImplPtr impl) : _impl(impl) { timeCallback = _defaultTimeCB; }
                  ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:241:5: error: 'FSImplPtr' does not name a type
     FSImplPtr _impl;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/FS.h:242:5: error: 'FSImplPtr' does not name a type
     FSImplPtr getImpl() { return _impl; }
     ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecure.h:41:0,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecure.h:20,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:41,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:203:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<br_ssl_client_context> _sc;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:204:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<br_ssl_server_context> _sc_svr;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:209:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<br_x509_minimal_context> _x509_minimal;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:210:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<struct br_x509_insecure_context> _x509_insecure;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:211:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<br_x509_knownkey_context> _x509_knownkey;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:212:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<unsigned char> _iobuf_in;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:213:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<unsigned char> _iobuf_out;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:226:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<X509List>   _axtls_ta;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:227:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<X509List>   _axtls_chain;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:228:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<PrivateKey> _axtls_sk;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:242:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<uint16_t> _cipher_list;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h: In member function 'bool BearSSL::WiFiClientSecure::ctx_present()':
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/complex.cpp.o
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:206:15: error: '_sc' was not declared in this scope
       return (_sc != nullptr) || (_sc_svr != nullptr);
               ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiClientSecureBearSSL.h:206:35: error: '_sc_svr' was not declared in this scope
       return (_sc != nullptr) || (_sc_svr != nullptr);
                                   ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecure.h:23:0,
                 from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/ESP8266WiFi.h:41,
                 from src/main.cpp:3:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h: At global scope:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h:78:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<X509List>   _axtls_chain;
     ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/libraries/ESP8266WiFi/src/WiFiServerSecureBearSSL.h:79:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<PrivateKey> _axtls_sk;
     ^
Compiling .pio/build/d1_mini/libacb/ArduinoSTL/del_op.cpp.o
*** [.pio/build/d1_mini/src/main.cpp.o] Error 1
.pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:79:2: warning: #warning "printf() will not be functional on this platform." [-Wcpp]
 #warning "printf() will not be functional on this platform."
  ^
In file included from /Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:246:0,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.h:12,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:1:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:53:13: error: 'function' in namespace 'std' does not name a type
     typedef std::function<void(size_t, size_t)> THandlerFunction_Progress;
             ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:19: error: expected ';' at end of member declaration
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                   ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:121:56: error: expected ')' before 'fn'
     UpdaterClass& onProgress(THandlerFunction_Progress fn);
                                                        ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Updater.h:204:5: error: 'THandlerFunction_Progress' does not name a type
     THandlerFunction_Progress _progress_callback;
     ^
In file included from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.h:12:0,
                 from .pio/libdeps/d1_mini/ArduinoSTL/src/ArduinoSTL.cpp:1:
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:251:12: error: 'std::isinf' has not been declared
 using std::isinf;
            ^
/Users/davidspeith/.platformio/packages/framework-arduinoespressif8266@2.20601.191124/cores/esp8266/Arduino.h:252:12: error: 'std::isnan' has not been declared
 using std::isnan;
            ^
*** [.pio/build/d1_mini/libacb/ArduinoSTL/ArduinoSTL.cpp.o] Error 1
================================================================================================================= [FAILED] Took 1.95 seconds =================================================================================================================

 *  The terminal process "platformio 'run', '--environment', 'd1_mini'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

´´´

**Comment by fabianoriccardi** [comment]
You can fix it by adding `lib_compat_mode = strict` in `platformio.ini`.

**Comment by heartwerker** [comment]
Great, thank you !
