### ISSUE TITLE
Use without zero cross?

### ISSUE THREAD

**Issue by Kclemen** [fabianoriccardi/dimmable-light#39]
Hi,

I want to use the script for an "15A mosfet pwm module". This board only contains a pin for PWM & GND. There is no pin for zero-cross.
Is there a way to make the script work anyway?

Example of the board: https://europe1.discourse-cdn.com/arduino/original/4X/9/5/3/953a157f9d8a6905f333cec75bad9375f36c88f8.jpeg

**Comment by fabianoriccardi** [comment]
Sorry for the late replay... I don't think that the board is a dimmer since it takes a DC voltage as input. You will need a common PWM signal (there are other libraries that handle PWM).
