### ISSUE TITLE
How many separate AC channels 

### ISSUE THREAD

**Issue by NikolaPU** [fabianoriccardi/dimmable-light#40]
Hi there, can you please answer?

How many separate AC channels can be controlled on arduino mega?
And how many separate AC channels can be controlled on ESP32?

Thanks in advance.
Best regards.

**Comment by fabianoriccardi** [comment]
Hi, I have tested up to 8 independent AC loads, but you should be able to increase that limit by changing a constant in thyristor.h

**Comment by radzikr** [comment]
I built an esp32 test pcb with 16 channels.

I'm currently assembling, I have 16 channels in the program, but currently 2 are soldered.

I think all 16 will work without any problem

**Comment by fabianoriccardi** [comment]
Great! When you will finish, if you can, may you share a photo of the setup?
